name: build

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: cmd

jobs:
  publish:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Check remal-packages.extension changes
      id: remal-packages-extension-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-packages.extension/
    - name: Publish remal-packages.extension
      if: ${{steps.remal-packages-extension-changes.outputs.any_changed == 'true' || steps.remal-packages-extension-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-packages.extension" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-hosts changes
      id: remal-hosts-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-hosts/
    - name: Publish remal-hosts
      if: ${{steps.remal-hosts-changes.outputs.any_changed == 'true' || steps.remal-hosts-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-hosts" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-cygwin changes
      id: remal-cygwin-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-cygwin/
    - name: Publish remal-cygwin
      if: ${{steps.remal-cygwin-changes.outputs.any_changed == 'true' || steps.remal-cygwin-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-cygwin" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check npp-compare changes
      id: npp-compare-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^npp-compare/
    - name: Publish npp-compare
      if: ${{steps.npp-compare-changes.outputs.any_changed == 'true' || steps.npp-compare-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "npp-compare" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check npp-editorconfig changes
      id: npp-editorconfig-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^npp-editorconfig/
    - name: Publish npp-editorconfig
      if: ${{steps.npp-editorconfig-changes.outputs.any_changed == 'true' || steps.npp-editorconfig-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "npp-editorconfig" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check npp-jstool changes
      id: npp-jstool-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^npp-jstool/
    - name: Publish npp-jstool
      if: ${{steps.npp-jstool-changes.outputs.any_changed == 'true' || steps.npp-jstool-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "npp-jstool" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-jdk8 changes
      id: remal-jdk8-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk8/
    - name: Publish remal-jdk8
      if: ${{steps.remal-jdk8-changes.outputs.any_changed == 'true' || steps.remal-jdk8-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-jdk8" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-jdk8-main changes
      id: remal-jdk8-main-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk8-main/
    - name: Publish remal-jdk8-main
      if: ${{steps.remal-jdk8-main-changes.outputs.any_changed == 'true' || steps.remal-jdk8-main-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-jdk8-main" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-jdk11 changes
      id: remal-jdk11-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk11/
    - name: Publish remal-jdk11
      if: ${{steps.remal-jdk11-changes.outputs.any_changed == 'true' || steps.remal-jdk11-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-jdk11" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-jdk11-main changes
      id: remal-jdk11-main-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk11-main/
    - name: Publish remal-jdk11-main
      if: ${{steps.remal-jdk11-main-changes.outputs.any_changed == 'true' || steps.remal-jdk11-main-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-jdk11-main" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-jdk17 changes
      id: remal-jdk17-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk17/
    - name: Publish remal-jdk17
      if: ${{steps.remal-jdk17-changes.outputs.any_changed == 'true' || steps.remal-jdk17-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-jdk17" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-jdk17-main changes
      id: remal-jdk17-main-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk17-main/
    - name: Publish remal-jdk17-main
      if: ${{steps.remal-jdk17-main-changes.outputs.any_changed == 'true' || steps.remal-jdk17-main-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-jdk17-main" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Check remal-root-editorconfig changes
      id: remal-root-editorconfig-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-root-editorconfig/
    - name: Publish remal-root-editorconfig
      if: ${{steps.remal-root-editorconfig-changes.outputs.any_changed == 'true' || steps.remal-root-editorconfig-changes.outputs.any_deleted == 'true'}}
      run: |
        pack-and-push "remal-root-editorconfig" "https://f.feedz.io/remal/chocolatey-packages/nuget" "${{secrets.FEEDZ_IO_TOKEN}}"

    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{env.PUSH_BACK_TOKEN && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')}}
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        message: '[push-back] Push-back updated files during build'
