name: build

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: cmd

jobs:
  publish:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Check remal-packages.extension changes
      id: remal-packages-extension-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-packages.extension/
    - name: Pack remal-packages.extension
      if: ${{steps.remal-packages-extension-changes.outputs.any_changed == 'true' || steps.remal-packages-extension-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack remal-packages.extension\remal-packages.extension.nuspec --outputdirectory .packed

    - name: Check npp-compare changes
      id: npp-compare-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^npp-compare/
    - name: Pack npp-compare
      if: ${{steps.npp-compare-changes.outputs.any_changed == 'true' || steps.npp-compare-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack npp-compare\npp-compare.nuspec --outputdirectory .packed

    - name: Check npp-editorconfig changes
      id: npp-editorconfig-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^npp-editorconfig/
    - name: Pack npp-editorconfig
      if: ${{steps.npp-editorconfig-changes.outputs.any_changed == 'true' || steps.npp-editorconfig-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack npp-editorconfig\npp-editorconfig.nuspec --outputdirectory .packed

    - name: Check npp-jstool changes
      id: npp-jstool-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^npp-jstool/
    - name: Pack npp-jstool
      if: ${{steps.npp-jstool-changes.outputs.any_changed == 'true' || steps.npp-jstool-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack npp-jstool\npp-jstool.nuspec --outputdirectory .packed

    - name: Check remal-jdk8 changes
      id: remal-jdk8-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk8/
    - name: Pack remal-jdk8
      if: ${{steps.remal-jdk8-changes.outputs.any_changed == 'true' || steps.remal-jdk8-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack remal-jdk8\remal-jdk8.nuspec --outputdirectory .packed

    - name: Check remal-jdk8-main changes
      id: remal-jdk8-main-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk8-main/
    - name: Pack remal-jdk8-main
      if: ${{steps.remal-jdk8-main-changes.outputs.any_changed == 'true' || steps.remal-jdk8-main-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack remal-jdk8-main\remal-jdk8-main.nuspec --outputdirectory .packed

    - name: Check remal-jdk11 changes
      id: remal-jdk11-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk11/
    - name: Pack remal-jdk11
      if: ${{steps.remal-jdk11-changes.outputs.any_changed == 'true' || steps.remal-jdk11-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack remal-jdk11\remal-jdk11.nuspec --outputdirectory .packed

    - name: Check remal-jdk11-main changes
      id: remal-jdk11-main-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk11-main/
    - name: Pack remal-jdk11-main
      if: ${{steps.remal-jdk11-main-changes.outputs.any_changed == 'true' || steps.remal-jdk11-main-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack remal-jdk11-main\remal-jdk11-main.nuspec --outputdirectory .packed

    - name: Check remal-jdk17 changes
      id: remal-jdk17-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk17/
    - name: Pack remal-jdk17
      if: ${{steps.remal-jdk17-changes.outputs.any_changed == 'true' || steps.remal-jdk17-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack remal-jdk17\remal-jdk17.nuspec --outputdirectory .packed

    - name: Check remal-jdk17-main changes
      id: remal-jdk17-main-changes
      uses: tj-actions/changed-files@v11.6
      with:
        files: ^remal-jdk17-main/
    - name: Pack remal-jdk17-main
      if: ${{steps.remal-jdk17-main-changes.outputs.any_changed == 'true' || steps.remal-jdk17-main-changes.outputs.any_deleted == 'true'}}
      run: |
        choco pack remal-jdk17-main\remal-jdk17-main.nuspec --outputdirectory .packed

    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
      if: ${{ env.PUSH_BACK_TOKEN && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{ env.PUSH_BACK_TOKEN }}
        message: '[push-back] Push-back updated files during build'
