name: generate-build-package-workflows

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  generate-build-package-workflows:
    name: generate-build-package-workflows
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Generate build package workflows
      run: |
        node generate-build-package-workflows.js
