name: generate-build-package-workflows

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  generate-build-package-workflows:
    if: ${{false}}
    name: generate-build-package-workflows
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Generate build package workflows
      run: |
        node generate-build-package-workflows.js
    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{env.PUSH_BACK_TOKEN && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')}}
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        message: 'Generated build package workflows'
